name: Deploy Databricks to PROD

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    environment:
      name: PROD

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate PROD Bundle
        run: databricks bundle validate -t prod

      - name: Deploy Databricks Bundle to PROD
        run: databricks bundle deploy -t prod